# Site settings
title: Eric J. Pabón Cancel
email: epabonca@purdue.edu
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ejpaboncancel.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

# Navigation bar
navbar-links:
Information: 
- title: "Research"
  href: "/research/"

- title: "Appearances"
  href: "/appearances/"

- title: "Hobbies"
  href: "/hobbies/"

- title: "CV"
  href: "/assets/CV_EricJPabonCancel"

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
